# Builds all the projects in the solution...
.PHONY: all_projects
all_projects: BattleCorp 

# Builds project 'BattleCorp'...
.PHONY: BattleCorp
BattleCorp: 
	make --directory="BattleMech/" --file=BattleCorp.makefile

# Cleans all projects...
.PHONY: clean
clean:
	make --directory="BattleMech/" --file=BattleCorp.makefile clean

